name: Package Release

on:
  push:
    tags:
        - '**'

env:
  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/chechkout@v1
      - uses: BigWigsMods/packager@master
